### ISSUE TITLE
config with keycloak

### ISSUE THREAD

**Issue by dmp2tech** [maildev/maildev#296]
Hi,

I use maildev 1.1.0 with docker. I configure keycloak that this.
<img width="879" alt="Capture d’écran 2020-04-22 à 13 15 36" src="https://user-images.githubusercontent.com/10258852/79975547-7373fd00-849b-11ea-9c3e-e1652769eb8b.png">
I have an error 
```
 com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost:1025, 25; timeout 10000;
  nested exception is:
	java.net.UnknownHostException: localhost:1025
```

I have redirect 1025 to 25 on docker.

Best regards

**Comment by RobertHeim** [comment]
If you use docker-compose you should use the container name rather than the localhost ip (which is the keycloak container itself).

```
version: '3.5'

services:

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
    ports:
      - ${KEYCLOAK_PORT:-9990}:8080
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - 1025:25
      - 1080:80
```
And then use `maildev` as host as shown in the image:

![image](https://user-images.githubusercontent.com/463840/89182087-456f8000-d595-11ea-8a58-19b65275ef5a.png)

![image](https://user-images.githubusercontent.com/463840/89182123-5ddf9a80-d595-11ea-8eb7-ad2ce537137e.png)
