### ISSUE TITLE
v2.0.0-beta3 not working with traefik

### ISSUE THREAD

**Issue by xavi-dev** [maildev/maildev#297]
In the v1.1.0, this dockerfile is working fine:
```
version: '3.7'

services:
  maildev:
    image: maildev/maildev:1.1.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maildev.rule=Host(`maildev.local`)"
      - "traefik.http.services.maildev.loadbalancer.server.port=80"
  traefik:
      image: traefik:2.2.0
      command:
        - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - '--providers.docker.watch=true'
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

You can try it with `docker-compose -f dockerfile.yml up -d --remove-orphans` adding `127.0.0.1 maildev.local` in your `hosts` file and browsing to `http://maildev.local`

![image](https://user-images.githubusercontent.com/3817677/80189333-cd4b0300-8612-11ea-8570-e8bc004f6e12.png)

The maildev service is on the traefik backend:

![image](https://user-images.githubusercontent.com/3817677/80189506-0edbae00-8613-11ea-83d5-36dea79c0da7.png)

But with the `2.0.0-beta3` version, traefik is not detecting anything:

```
version: '3.7'

services:
  maildev:
    image: maildev/maildev:2.0.0-beta3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maildev.rule=Host(`maildev.local`)"
      - "traefik.http.services.maildev.loadbalancer.server.port=1080"
  traefik:
      image: traefik:2.2.0
      command:
        - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - '--providers.docker.watch=true'
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
![image](https://user-images.githubusercontent.com/3817677/80189675-582bfd80-8613-11ea-96de-6d8089f2c818.png)

It doe not matter which port or expose  on the maildev service… traefik is never detecting the image

**Comment by jonathonwalz** [comment]
The healthcheck is broken due to curl not getting installed in the prod image (7d4556d and 3d789ad are the relevant commits).

A simple work around is to update your docker-compose file to change the health check:

```yaml
maildev:
    image: "maildev/maildev:2.0.0-beta3"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:1080/healthz"]
```
