### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by Zacktagnan-ZubiMan** [maildev/maildev#301]
Hi:

I am implementing a Laravel project with an email section. I would use your application to test the sending email process.
To get MailDev up, I choose the Docker version so I execute this command on a CMD of Windows:

```
C:\Users\myuser>docker run -p 1080:80 -p 1025:25 --name maildev maildev/maildev
MailDev webapp running at http://0.0.0.0:80
MailDev SMTP Server running at 0.0.0.0:25
```

The Laravel project itself is started through a series of Docker Compose services. So, it's a communication between Docker containers.
Nginx is the web server.

On the ".env" file of my Laravel project, I have this configuration:

```
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
# MAIL_PORT=25
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

When I get the order to send the mail, I received this error on the browser:

> **Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:1025 (Connection refused)**

Why the MailDev app doesn't works on my local environment?

**Comment by Zacktagnan-ZubiMan** [comment]
Well, finally that solve the problem I had.

First, it's better to add the MailDev inside the same "docker-compose.yml" of the other services.
The MailDev service block is set like this:

```
  # MailDev
  The service name that you want; it has to be referenced inside the Laravel ".env" file
  ####maildev:
  maildev_server:
    image: maildev/maildev
    container_name: cont_maildev_server
    #This is opcional
    tty: true
    ports:
      - '1080:80'
    #This is optional
    #restart: always
    restart: on-failure
    #The same network of the others services
    networks:
      - net
```

Inside the ".env" file the environment variable had to be like that:

```
MAIL_MAILER=smtp
#NOT that
#MAIL_HOST=127.0.0.1
#but this
MAIL_HOST=maildev_server
#This is the fine port
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

After save the changes, maybe, it would be necessary to cleanning the cache project, so:

`php artisan config:cache`

And that's all!!

Thanks to the person who helps me to solve the problem outside this GitHub.
I hope this should help someone else.

Bye.
