### ISSUE TITLE
MAILDEV_AUTO_RELAY stop working after x mails

### ISSUE THREAD

**Issue by FlochonR** [maildev/maildev#423]
Hello !

I'm using Maildev in a docker-compose and I'm getting a mistake.
After 700-800 mails received in Maildev, it doesn't relay mail anymore.
Before the 700-800 mails all is ok, I have no problem.

Here my config:
docker-compose.yml
```
version: '3.8'

services:
  maildev:
    image: maildev/maildev:${MAILDEV_VERSION}
    restart: always
    ports:
      - "25:1025"
    env_file:
      - .env
```
.env
```
MAILDEV_VERSION=2.0.5

MAILDEV_OUTGOING_HOST=toto
MAILDEV_OUTGOING_PORT=25
MAILDEV_AUTO_RELAY=True

SMF_CONFIG=@toto.dev:github@toto.com
SMF_RELAYHOST=toto.github.com
```

Someone already had this issue ? Or seeing a problem in my configuration ?

Thanks for your reply,
FlochonR
