### ISSUE TITLE
Docker HealthCheck failing on custom web port

### ISSUE THREAD

**Issue by Pwnobbypure** [maildev/maildev#438]
The HealthCheck url currently seems to be hardcoded to port 1080
```
HEALTHCHECK --interval=10s --timeout=1s \
  CMD wget -O - http://localhost:1080/healthz || exit 1
```

Since we can supply a custom web port for maildev with the `MAILDEV_WEB_PORT` environment variable, this means that the HealthCheck will start failing because maildev is no longer listening to port 1080 for internal web traffic.

I'm wondering if the port used in the HealthCheck url should reference the environment variable instead of being hardcoded as 1080?

**Comment by enyosolutions** [comment]
You can change the port to whatever you like using docker compose


```
    healthcheck:
      test: ['CMD', 'wget', '-O -', 'http://localhost:80/healthz']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
```
