### ISSUE TITLE
Docker not supporting  option `--mail-directory'

### ISSUE THREAD

**Issue by sschuetz2bit** [maildev/maildev#452]
When using maildev with  the latest docker image i get : Error: unknown option `--mail-directory'

**Comment by bjoern-hempel** [comment]
In Docker Compose, this parameter works absolutely fine. Here is an example:

```yaml
  maildev:
    image: "maildev/maildev:latest"
    container_name: "maildev"
    hostname: "maildev"
    command: ["--mail-directory=/maildir"]
    volumes:
      - maildev-data:/maildir
    restart: always
    networks:
      - network-internal
    depends_on:
      - php

volumes:
  maildev-data:
    name: "maildev.data"
```

Be sure to change the directory permissions afterwards:

```bash
docker compose exec -u root maildev sh
```

Within the container:

```bash
chown -R node:node maildir/
chmod -R 775 maildir/
```

**Comment by djfarrelly** [comment]
`--mail-directory` is a supported option on the current release (and there's also a `MAILDEV_MAIL_DIRECTORY` env var and a `mailDirectory` config-file key). The 2023 "unknown option" error was from the Docker image lagging behind master at the time; current `maildev/maildev` images include it.

As the thread shows, it works in Docker Compose via the service `command`, e.g.:

```yaml
services:
  maildev:
    image: maildev/maildev:latest
    command: ["--mail-directory", "/home/node/data", "--web", "1080", "--smtp", "1025"]
    volumes:
      - ./maildev-data:/home/node/data
```

Closing as resolved.
