### ISSUE TITLE
Health check problem with MAILDEV_BASE_PATHNAME, MAILDEV_WEB_USER and MAILDEV_WEB_PASS

### ISSUE THREAD

**Issue by nicolasiannarilli** [maildev/maildev#474]
Health check needs basic auth when MAILDEV_BASE_PATHNAME, MAILDEV_WEB_USER and MAILDEV_WEB_PASS are active.

I think the problem is in auths.js :
```
 // allow health checks without auth
    if (req.path === '/healthz') {
      return next()
    }
``` 
doesn't works with MAILDEV_BASE_PATHNAME.

to reproduce :
with docker-compose.yml
```yml
maildev:
    image: maildev/maildev:latest # latest = 2.1.0
    container_name: maildev
    environment:
      MAILDEV_BASE_PATHNAME: "/mail"
      MAILDEV_WEB_USER: "maildev"
      MAILDEV_WEB_PASS: "maildev"
    ports:
      - "1080:80"
      # - "1025:25"
```
command :
```    
docker-compose up -d maildev
docker-compose exec maildev wget -O - http://localhost:1080/mail/healthz
```
result :
```
wget: server returned error: HTTP/1.1 401 Unauthorized
```
