### ISSUE TITLE
Auto relay doesn't auto relay

### ISSUE THREAD

**Issue by shugyosha89** [maildev/maildev#493]
Auto relay doesn't relay emails to addresses that are configured to be automatically relayed.

I'm using the Docker image.

Full Docker compose:
```
  maildev:
    image: maildev/maildev
    container_name: maildev
    environment:
      MAILDEV_MAIL_DIRECTORY: /mail
      MAILDEV_OUTGOING_HOST: <smtp server>
      MAILDEV_OUTGOING_PORT: 587
      MAILDEV_OUTGOING_USER: <smtp user>
      MAILDEV_OUTGOING_PASS: <smtp password>
      MAILDEV_OUTGOING_SECURE: true
      MAILDEV_AUTO_RELAY: true
      MAILDEV_AUTO_RELAY_RULES: /config/auto-relay.json
      MAILDEV_INCOMING_USER: <a username>
      MAILDEV_INCOMING_PASS: <a password>
      MAILDEV_INCOMING_SECURE: true
      MAILDEV_INCOMING_CERT: /config/maildev.crt
      MAILDEV_INCOMING_KEY: /config/maildev.key
    volumes:
      - /docker/maildev/mail:/mail
      - /docker/maildev/config:/config
    ports:
      - 1025:1025
      - 1080:1080
```

Contents of auto-relay.json (domain edited for privacy):
```
[
  { "deny": "*" },
  { "allow": "*@mydomain.com" }
]
```

Sending an email to e.g. test@mydomain.com does not relay.

Clicking "Relay" on the web app also does not relay. However, clicking "Relay To" and entering an email address does relay.

Possibly shares a cause with #491.
